baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Dhan V Sagar'
theme = "anatole"

[params]
title = "I'm Dhan V Sagar"
author = "Dhan V Sagar"
description = "Call me Dhan"
profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


copyright = "2020-{{ YEAR }}"
